# Generated by Django 5.1.7 on 2025-04-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0002_rename_backgorund_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='image',
            field=models.ImageField(upload_to='backgrounds'),
        ),
    ]
