# Generated by Django 5.1.7 on 2025-04-29 21:20

import Paths.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0004_path_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='bg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Paths.background'),
        ),
        migrations.AlterField(
            model_name='path',
            name='user',
            field=models.ForeignKey(default=Paths.models.get_default_superuser, on_delete=django.db.models.deletion.CASCADE, related_name='paths', to=settings.AUTH_USER_MODEL),
        ),
    ]
