# Generated by Django 5.1.7 on 2025-04-29 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0005_alter_path_bg_alter_path_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='path',
            old_name='bg',
            new_name='background',
        ),
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Paths.background')),
            ],
        ),
    ]
