# Generated by Django 5.1.7 on 2025-05-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0008_gameboard_dot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotsJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dots', models.JSONField()),
            ],
        ),
    ]
